package com.zzc.hpnote.dao;

import com.zzc.hpnote.domain.ParamDefine;
import com.zzc.hpnote.domain.ParamDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int countByExample(ParamDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int deleteByExample(ParamDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int insert(ParamDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int insertSelective(ParamDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    List<ParamDefine> selectByExample(ParamDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    ParamDefine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") ParamDefine record, @Param("example") ParamDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int updateByExample(@Param("record") ParamDefine record, @Param("example") ParamDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int updateByPrimaryKeySelective(ParamDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_define
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int updateByPrimaryKey(ParamDefine record);
}