package com.zzc.hpnote.dao;

import com.zzc.hpnote.domain.PriceInfo;
import com.zzc.hpnote.domain.PriceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PriceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int countByExample(PriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int deleteByExample(PriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int insert(PriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int insertSelective(PriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    List<PriceInfo> selectByExample(PriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") PriceInfo record, @Param("example") PriceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    int updateByExample(@Param("record") PriceInfo record, @Param("example") PriceInfoExample example);
}