package com.zzc.hpnote.dao;

import com.zzc.hpnote.domain.TaskConf;
import com.zzc.hpnote.domain.TaskConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int countByExample(TaskConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int deleteByExample(TaskConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int insert(TaskConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int insertSelective(TaskConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    List<TaskConf> selectByExample(TaskConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    TaskConf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") TaskConf record, @Param("example") TaskConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int updateByExample(@Param("record") TaskConf record, @Param("example") TaskConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int updateByPrimaryKeySelective(TaskConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_conf
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    int updateByPrimaryKey(TaskConf record);
}