package com.zzc.hpnote.domain;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.AREA_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.AREA_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.PARENT_AREA_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String parentAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.PARENT_AREA_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String parentAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.REGION_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.REGION_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.PARENT_REGION_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String parentRegionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.PARENT_REGION_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String parentRegionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.REMARK
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.AREA_CODE
     *
     * @return the value of area.AREA_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.AREA_CODE
     *
     * @param areaCode the value for area.AREA_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.AREA_NAME
     *
     * @return the value of area.AREA_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.AREA_NAME
     *
     * @param areaName the value for area.AREA_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.PARENT_AREA_CODE
     *
     * @return the value of area.PARENT_AREA_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getParentAreaCode() {
        return parentAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.PARENT_AREA_CODE
     *
     * @param parentAreaCode the value for area.PARENT_AREA_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setParentAreaCode(String parentAreaCode) {
        this.parentAreaCode = parentAreaCode == null ? null : parentAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.PARENT_AREA_NAME
     *
     * @return the value of area.PARENT_AREA_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getParentAreaName() {
        return parentAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.PARENT_AREA_NAME
     *
     * @param parentAreaName the value for area.PARENT_AREA_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setParentAreaName(String parentAreaName) {
        this.parentAreaName = parentAreaName == null ? null : parentAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.REGION_CODE
     *
     * @return the value of area.REGION_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.REGION_CODE
     *
     * @param regionCode the value for area.REGION_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.REGION_NAME
     *
     * @return the value of area.REGION_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.REGION_NAME
     *
     * @param regionName the value for area.REGION_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.PARENT_REGION_CODE
     *
     * @return the value of area.PARENT_REGION_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getParentRegionCode() {
        return parentRegionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.PARENT_REGION_CODE
     *
     * @param parentRegionCode the value for area.PARENT_REGION_CODE
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setParentRegionCode(String parentRegionCode) {
        this.parentRegionCode = parentRegionCode == null ? null : parentRegionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.PARENT_REGION_NAME
     *
     * @return the value of area.PARENT_REGION_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getParentRegionName() {
        return parentRegionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.PARENT_REGION_NAME
     *
     * @param parentRegionName the value for area.PARENT_REGION_NAME
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setParentRegionName(String parentRegionName) {
        this.parentRegionName = parentRegionName == null ? null : parentRegionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.REMARK
     *
     * @return the value of area.REMARK
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.REMARK
     *
     * @param remark the value for area.REMARK
     *
     * @mbggenerated Sat May 17 15:35:02 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}