package com.zzc.hpnote.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public BaseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHIdIsNull() {
            addCriterion("H_ID is null");
            return (Criteria) this;
        }

        public Criteria andHIdIsNotNull() {
            addCriterion("H_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHIdEqualTo(String value) {
            addCriterion("H_ID =", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotEqualTo(String value) {
            addCriterion("H_ID <>", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdGreaterThan(String value) {
            addCriterion("H_ID >", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdGreaterThanOrEqualTo(String value) {
            addCriterion("H_ID >=", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdLessThan(String value) {
            addCriterion("H_ID <", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdLessThanOrEqualTo(String value) {
            addCriterion("H_ID <=", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdLike(String value) {
            addCriterion("H_ID like", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotLike(String value) {
            addCriterion("H_ID not like", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdIn(List<String> values) {
            addCriterion("H_ID in", values, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotIn(List<String> values) {
            addCriterion("H_ID not in", values, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdBetween(String value1, String value2) {
            addCriterion("H_ID between", value1, value2, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotBetween(String value1, String value2) {
            addCriterion("H_ID not between", value1, value2, "hId");
            return (Criteria) this;
        }

        public Criteria andHTRoomIsNull() {
            addCriterion("H_T_ROOM is null");
            return (Criteria) this;
        }

        public Criteria andHTRoomIsNotNull() {
            addCriterion("H_T_ROOM is not null");
            return (Criteria) this;
        }

        public Criteria andHTRoomEqualTo(Integer value) {
            addCriterion("H_T_ROOM =", value, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomNotEqualTo(Integer value) {
            addCriterion("H_T_ROOM <>", value, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomGreaterThan(Integer value) {
            addCriterion("H_T_ROOM >", value, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomGreaterThanOrEqualTo(Integer value) {
            addCriterion("H_T_ROOM >=", value, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomLessThan(Integer value) {
            addCriterion("H_T_ROOM <", value, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomLessThanOrEqualTo(Integer value) {
            addCriterion("H_T_ROOM <=", value, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomIn(List<Integer> values) {
            addCriterion("H_T_ROOM in", values, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomNotIn(List<Integer> values) {
            addCriterion("H_T_ROOM not in", values, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomBetween(Integer value1, Integer value2) {
            addCriterion("H_T_ROOM between", value1, value2, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTRoomNotBetween(Integer value1, Integer value2) {
            addCriterion("H_T_ROOM not between", value1, value2, "hTRoom");
            return (Criteria) this;
        }

        public Criteria andHTHallIsNull() {
            addCriterion("H_T_HALL is null");
            return (Criteria) this;
        }

        public Criteria andHTHallIsNotNull() {
            addCriterion("H_T_HALL is not null");
            return (Criteria) this;
        }

        public Criteria andHTHallEqualTo(Integer value) {
            addCriterion("H_T_HALL =", value, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallNotEqualTo(Integer value) {
            addCriterion("H_T_HALL <>", value, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallGreaterThan(Integer value) {
            addCriterion("H_T_HALL >", value, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallGreaterThanOrEqualTo(Integer value) {
            addCriterion("H_T_HALL >=", value, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallLessThan(Integer value) {
            addCriterion("H_T_HALL <", value, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallLessThanOrEqualTo(Integer value) {
            addCriterion("H_T_HALL <=", value, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallIn(List<Integer> values) {
            addCriterion("H_T_HALL in", values, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallNotIn(List<Integer> values) {
            addCriterion("H_T_HALL not in", values, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallBetween(Integer value1, Integer value2) {
            addCriterion("H_T_HALL between", value1, value2, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTHallNotBetween(Integer value1, Integer value2) {
            addCriterion("H_T_HALL not between", value1, value2, "hTHall");
            return (Criteria) this;
        }

        public Criteria andHTKitchenIsNull() {
            addCriterion("H_T_KITCHEN is null");
            return (Criteria) this;
        }

        public Criteria andHTKitchenIsNotNull() {
            addCriterion("H_T_KITCHEN is not null");
            return (Criteria) this;
        }

        public Criteria andHTKitchenEqualTo(Integer value) {
            addCriterion("H_T_KITCHEN =", value, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenNotEqualTo(Integer value) {
            addCriterion("H_T_KITCHEN <>", value, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenGreaterThan(Integer value) {
            addCriterion("H_T_KITCHEN >", value, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenGreaterThanOrEqualTo(Integer value) {
            addCriterion("H_T_KITCHEN >=", value, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenLessThan(Integer value) {
            addCriterion("H_T_KITCHEN <", value, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenLessThanOrEqualTo(Integer value) {
            addCriterion("H_T_KITCHEN <=", value, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenIn(List<Integer> values) {
            addCriterion("H_T_KITCHEN in", values, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenNotIn(List<Integer> values) {
            addCriterion("H_T_KITCHEN not in", values, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenBetween(Integer value1, Integer value2) {
            addCriterion("H_T_KITCHEN between", value1, value2, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTKitchenNotBetween(Integer value1, Integer value2) {
            addCriterion("H_T_KITCHEN not between", value1, value2, "hTKitchen");
            return (Criteria) this;
        }

        public Criteria andHTBathroomIsNull() {
            addCriterion("H_T_BATHROOM is null");
            return (Criteria) this;
        }

        public Criteria andHTBathroomIsNotNull() {
            addCriterion("H_T_BATHROOM is not null");
            return (Criteria) this;
        }

        public Criteria andHTBathroomEqualTo(Integer value) {
            addCriterion("H_T_BATHROOM =", value, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomNotEqualTo(Integer value) {
            addCriterion("H_T_BATHROOM <>", value, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomGreaterThan(Integer value) {
            addCriterion("H_T_BATHROOM >", value, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomGreaterThanOrEqualTo(Integer value) {
            addCriterion("H_T_BATHROOM >=", value, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomLessThan(Integer value) {
            addCriterion("H_T_BATHROOM <", value, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomLessThanOrEqualTo(Integer value) {
            addCriterion("H_T_BATHROOM <=", value, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomIn(List<Integer> values) {
            addCriterion("H_T_BATHROOM in", values, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomNotIn(List<Integer> values) {
            addCriterion("H_T_BATHROOM not in", values, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomBetween(Integer value1, Integer value2) {
            addCriterion("H_T_BATHROOM between", value1, value2, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andHTBathroomNotBetween(Integer value1, Integer value2) {
            addCriterion("H_T_BATHROOM not between", value1, value2, "hTBathroom");
            return (Criteria) this;
        }

        public Criteria andRoomSizeIsNull() {
            addCriterion("ROOM_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andRoomSizeIsNotNull() {
            addCriterion("ROOM_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomSizeEqualTo(Float value) {
            addCriterion("ROOM_SIZE =", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeNotEqualTo(Float value) {
            addCriterion("ROOM_SIZE <>", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeGreaterThan(Float value) {
            addCriterion("ROOM_SIZE >", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeGreaterThanOrEqualTo(Float value) {
            addCriterion("ROOM_SIZE >=", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeLessThan(Float value) {
            addCriterion("ROOM_SIZE <", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeLessThanOrEqualTo(Float value) {
            addCriterion("ROOM_SIZE <=", value, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeIn(List<Float> values) {
            addCriterion("ROOM_SIZE in", values, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeNotIn(List<Float> values) {
            addCriterion("ROOM_SIZE not in", values, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeBetween(Float value1, Float value2) {
            addCriterion("ROOM_SIZE between", value1, value2, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomSizeNotBetween(Float value1, Float value2) {
            addCriterion("ROOM_SIZE not between", value1, value2, "roomSize");
            return (Criteria) this;
        }

        public Criteria andRoomAgeIsNull() {
            addCriterion("ROOM_AGE is null");
            return (Criteria) this;
        }

        public Criteria andRoomAgeIsNotNull() {
            addCriterion("ROOM_AGE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomAgeEqualTo(Integer value) {
            addCriterion("ROOM_AGE =", value, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeNotEqualTo(Integer value) {
            addCriterion("ROOM_AGE <>", value, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeGreaterThan(Integer value) {
            addCriterion("ROOM_AGE >", value, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROOM_AGE >=", value, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeLessThan(Integer value) {
            addCriterion("ROOM_AGE <", value, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeLessThanOrEqualTo(Integer value) {
            addCriterion("ROOM_AGE <=", value, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeIn(List<Integer> values) {
            addCriterion("ROOM_AGE in", values, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeNotIn(List<Integer> values) {
            addCriterion("ROOM_AGE not in", values, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_AGE between", value1, value2, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_AGE not between", value1, value2, "roomAge");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsIsNull() {
            addCriterion("ROOM_TOWARDS is null");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsIsNotNull() {
            addCriterion("ROOM_TOWARDS is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsEqualTo(String value) {
            addCriterion("ROOM_TOWARDS =", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsNotEqualTo(String value) {
            addCriterion("ROOM_TOWARDS <>", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsGreaterThan(String value) {
            addCriterion("ROOM_TOWARDS >", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_TOWARDS >=", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsLessThan(String value) {
            addCriterion("ROOM_TOWARDS <", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsLessThanOrEqualTo(String value) {
            addCriterion("ROOM_TOWARDS <=", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsLike(String value) {
            addCriterion("ROOM_TOWARDS like", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsNotLike(String value) {
            addCriterion("ROOM_TOWARDS not like", value, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsIn(List<String> values) {
            addCriterion("ROOM_TOWARDS in", values, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsNotIn(List<String> values) {
            addCriterion("ROOM_TOWARDS not in", values, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsBetween(String value1, String value2) {
            addCriterion("ROOM_TOWARDS between", value1, value2, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomTowardsNotBetween(String value1, String value2) {
            addCriterion("ROOM_TOWARDS not between", value1, value2, "roomTowards");
            return (Criteria) this;
        }

        public Criteria andRoomFloorIsNull() {
            addCriterion("ROOM_FLOOR is null");
            return (Criteria) this;
        }

        public Criteria andRoomFloorIsNotNull() {
            addCriterion("ROOM_FLOOR is not null");
            return (Criteria) this;
        }

        public Criteria andRoomFloorEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR =", value, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorNotEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR <>", value, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorGreaterThan(Integer value) {
            addCriterion("ROOM_FLOOR >", value, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR >=", value, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorLessThan(Integer value) {
            addCriterion("ROOM_FLOOR <", value, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorLessThanOrEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR <=", value, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorIn(List<Integer> values) {
            addCriterion("ROOM_FLOOR in", values, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorNotIn(List<Integer> values) {
            addCriterion("ROOM_FLOOR not in", values, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_FLOOR between", value1, value2, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorNotBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_FLOOR not between", value1, value2, "roomFloor");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalIsNull() {
            addCriterion("ROOM_FLOOR_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalIsNotNull() {
            addCriterion("ROOM_FLOOR_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR_TOTAL =", value, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalNotEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR_TOTAL <>", value, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalGreaterThan(Integer value) {
            addCriterion("ROOM_FLOOR_TOTAL >", value, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR_TOTAL >=", value, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalLessThan(Integer value) {
            addCriterion("ROOM_FLOOR_TOTAL <", value, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalLessThanOrEqualTo(Integer value) {
            addCriterion("ROOM_FLOOR_TOTAL <=", value, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalIn(List<Integer> values) {
            addCriterion("ROOM_FLOOR_TOTAL in", values, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalNotIn(List<Integer> values) {
            addCriterion("ROOM_FLOOR_TOTAL not in", values, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_FLOOR_TOTAL between", value1, value2, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomFloorTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("ROOM_FLOOR_TOTAL not between", value1, value2, "roomFloorTotal");
            return (Criteria) this;
        }

        public Criteria andRoomStructureIsNull() {
            addCriterion("ROOM_STRUCTURE is null");
            return (Criteria) this;
        }

        public Criteria andRoomStructureIsNotNull() {
            addCriterion("ROOM_STRUCTURE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomStructureEqualTo(String value) {
            addCriterion("ROOM_STRUCTURE =", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureNotEqualTo(String value) {
            addCriterion("ROOM_STRUCTURE <>", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureGreaterThan(String value) {
            addCriterion("ROOM_STRUCTURE >", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_STRUCTURE >=", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureLessThan(String value) {
            addCriterion("ROOM_STRUCTURE <", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureLessThanOrEqualTo(String value) {
            addCriterion("ROOM_STRUCTURE <=", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureLike(String value) {
            addCriterion("ROOM_STRUCTURE like", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureNotLike(String value) {
            addCriterion("ROOM_STRUCTURE not like", value, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureIn(List<String> values) {
            addCriterion("ROOM_STRUCTURE in", values, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureNotIn(List<String> values) {
            addCriterion("ROOM_STRUCTURE not in", values, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureBetween(String value1, String value2) {
            addCriterion("ROOM_STRUCTURE between", value1, value2, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomStructureNotBetween(String value1, String value2) {
            addCriterion("ROOM_STRUCTURE not between", value1, value2, "roomStructure");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateIsNull() {
            addCriterion("ROOM_DECORATE is null");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateIsNotNull() {
            addCriterion("ROOM_DECORATE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateEqualTo(String value) {
            addCriterion("ROOM_DECORATE =", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateNotEqualTo(String value) {
            addCriterion("ROOM_DECORATE <>", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateGreaterThan(String value) {
            addCriterion("ROOM_DECORATE >", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_DECORATE >=", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateLessThan(String value) {
            addCriterion("ROOM_DECORATE <", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateLessThanOrEqualTo(String value) {
            addCriterion("ROOM_DECORATE <=", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateLike(String value) {
            addCriterion("ROOM_DECORATE like", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateNotLike(String value) {
            addCriterion("ROOM_DECORATE not like", value, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateIn(List<String> values) {
            addCriterion("ROOM_DECORATE in", values, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateNotIn(List<String> values) {
            addCriterion("ROOM_DECORATE not in", values, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateBetween(String value1, String value2) {
            addCriterion("ROOM_DECORATE between", value1, value2, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomDecorateNotBetween(String value1, String value2) {
            addCriterion("ROOM_DECORATE not between", value1, value2, "roomDecorate");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIsNull() {
            addCriterion("ROOM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIsNotNull() {
            addCriterion("ROOM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeEqualTo(String value) {
            addCriterion("ROOM_TYPE =", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotEqualTo(String value) {
            addCriterion("ROOM_TYPE <>", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeGreaterThan(String value) {
            addCriterion("ROOM_TYPE >", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_TYPE >=", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLessThan(String value) {
            addCriterion("ROOM_TYPE <", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLessThanOrEqualTo(String value) {
            addCriterion("ROOM_TYPE <=", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeLike(String value) {
            addCriterion("ROOM_TYPE like", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotLike(String value) {
            addCriterion("ROOM_TYPE not like", value, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeIn(List<String> values) {
            addCriterion("ROOM_TYPE in", values, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotIn(List<String> values) {
            addCriterion("ROOM_TYPE not in", values, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeBetween(String value1, String value2) {
            addCriterion("ROOM_TYPE between", value1, value2, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNotBetween(String value1, String value2) {
            addCriterion("ROOM_TYPE not between", value1, value2, "roomType");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyIsNull() {
            addCriterion("ROOM_PROPERTY is null");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyIsNotNull() {
            addCriterion("ROOM_PROPERTY is not null");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyEqualTo(String value) {
            addCriterion("ROOM_PROPERTY =", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyNotEqualTo(String value) {
            addCriterion("ROOM_PROPERTY <>", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyGreaterThan(String value) {
            addCriterion("ROOM_PROPERTY >", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_PROPERTY >=", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyLessThan(String value) {
            addCriterion("ROOM_PROPERTY <", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyLessThanOrEqualTo(String value) {
            addCriterion("ROOM_PROPERTY <=", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyLike(String value) {
            addCriterion("ROOM_PROPERTY like", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyNotLike(String value) {
            addCriterion("ROOM_PROPERTY not like", value, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyIn(List<String> values) {
            addCriterion("ROOM_PROPERTY in", values, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyNotIn(List<String> values) {
            addCriterion("ROOM_PROPERTY not in", values, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyBetween(String value1, String value2) {
            addCriterion("ROOM_PROPERTY between", value1, value2, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomPropertyNotBetween(String value1, String value2) {
            addCriterion("ROOM_PROPERTY not between", value1, value2, "roomProperty");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureIsNull() {
            addCriterion("ROOM_FEATURE is null");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureIsNotNull() {
            addCriterion("ROOM_FEATURE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureEqualTo(String value) {
            addCriterion("ROOM_FEATURE =", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureNotEqualTo(String value) {
            addCriterion("ROOM_FEATURE <>", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureGreaterThan(String value) {
            addCriterion("ROOM_FEATURE >", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_FEATURE >=", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureLessThan(String value) {
            addCriterion("ROOM_FEATURE <", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureLessThanOrEqualTo(String value) {
            addCriterion("ROOM_FEATURE <=", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureLike(String value) {
            addCriterion("ROOM_FEATURE like", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureNotLike(String value) {
            addCriterion("ROOM_FEATURE not like", value, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureIn(List<String> values) {
            addCriterion("ROOM_FEATURE in", values, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureNotIn(List<String> values) {
            addCriterion("ROOM_FEATURE not in", values, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureBetween(String value1, String value2) {
            addCriterion("ROOM_FEATURE between", value1, value2, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomFeatureNotBetween(String value1, String value2) {
            addCriterion("ROOM_FEATURE not between", value1, value2, "roomFeature");
            return (Criteria) this;
        }

        public Criteria andRoomAgentIsNull() {
            addCriterion("ROOM_AGENT is null");
            return (Criteria) this;
        }

        public Criteria andRoomAgentIsNotNull() {
            addCriterion("ROOM_AGENT is not null");
            return (Criteria) this;
        }

        public Criteria andRoomAgentEqualTo(String value) {
            addCriterion("ROOM_AGENT =", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentNotEqualTo(String value) {
            addCriterion("ROOM_AGENT <>", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentGreaterThan(String value) {
            addCriterion("ROOM_AGENT >", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_AGENT >=", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentLessThan(String value) {
            addCriterion("ROOM_AGENT <", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentLessThanOrEqualTo(String value) {
            addCriterion("ROOM_AGENT <=", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentLike(String value) {
            addCriterion("ROOM_AGENT like", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentNotLike(String value) {
            addCriterion("ROOM_AGENT not like", value, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentIn(List<String> values) {
            addCriterion("ROOM_AGENT in", values, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentNotIn(List<String> values) {
            addCriterion("ROOM_AGENT not in", values, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentBetween(String value1, String value2) {
            addCriterion("ROOM_AGENT between", value1, value2, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomAgentNotBetween(String value1, String value2) {
            addCriterion("ROOM_AGENT not between", value1, value2, "roomAgent");
            return (Criteria) this;
        }

        public Criteria andRoomTitleIsNull() {
            addCriterion("ROOM_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andRoomTitleIsNotNull() {
            addCriterion("ROOM_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTitleEqualTo(String value) {
            addCriterion("ROOM_TITLE =", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleNotEqualTo(String value) {
            addCriterion("ROOM_TITLE <>", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleGreaterThan(String value) {
            addCriterion("ROOM_TITLE >", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_TITLE >=", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleLessThan(String value) {
            addCriterion("ROOM_TITLE <", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleLessThanOrEqualTo(String value) {
            addCriterion("ROOM_TITLE <=", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleLike(String value) {
            addCriterion("ROOM_TITLE like", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleNotLike(String value) {
            addCriterion("ROOM_TITLE not like", value, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleIn(List<String> values) {
            addCriterion("ROOM_TITLE in", values, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleNotIn(List<String> values) {
            addCriterion("ROOM_TITLE not in", values, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleBetween(String value1, String value2) {
            addCriterion("ROOM_TITLE between", value1, value2, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andRoomTitleNotBetween(String value1, String value2) {
            addCriterion("ROOM_TITLE not between", value1, value2, "roomTitle");
            return (Criteria) this;
        }

        public Criteria andViewTimeIsNull() {
            addCriterion("VIEW_TIME is null");
            return (Criteria) this;
        }

        public Criteria andViewTimeIsNotNull() {
            addCriterion("VIEW_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andViewTimeEqualTo(String value) {
            addCriterion("VIEW_TIME =", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeNotEqualTo(String value) {
            addCriterion("VIEW_TIME <>", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeGreaterThan(String value) {
            addCriterion("VIEW_TIME >", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeGreaterThanOrEqualTo(String value) {
            addCriterion("VIEW_TIME >=", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeLessThan(String value) {
            addCriterion("VIEW_TIME <", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeLessThanOrEqualTo(String value) {
            addCriterion("VIEW_TIME <=", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeLike(String value) {
            addCriterion("VIEW_TIME like", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeNotLike(String value) {
            addCriterion("VIEW_TIME not like", value, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeIn(List<String> values) {
            addCriterion("VIEW_TIME in", values, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeNotIn(List<String> values) {
            addCriterion("VIEW_TIME not in", values, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeBetween(String value1, String value2) {
            addCriterion("VIEW_TIME between", value1, value2, "viewTime");
            return (Criteria) this;
        }

        public Criteria andViewTimeNotBetween(String value1, String value2) {
            addCriterion("VIEW_TIME not between", value1, value2, "viewTime");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNull() {
            addCriterion("PROJECT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNotNull() {
            addCriterion("PROJECT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeEqualTo(String value) {
            addCriterion("PROJECT_TYPE =", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotEqualTo(String value) {
            addCriterion("PROJECT_TYPE <>", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThan(String value) {
            addCriterion("PROJECT_TYPE >", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_TYPE >=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThan(String value) {
            addCriterion("PROJECT_TYPE <", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_TYPE <=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLike(String value) {
            addCriterion("PROJECT_TYPE like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotLike(String value) {
            addCriterion("PROJECT_TYPE not like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIn(List<String> values) {
            addCriterion("PROJECT_TYPE in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotIn(List<String> values) {
            addCriterion("PROJECT_TYPE not in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeBetween(String value1, String value2) {
            addCriterion("PROJECT_TYPE between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotBetween(String value1, String value2) {
            addCriterion("PROJECT_TYPE not between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("PROJECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("PROJECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("PROJECT_NAME =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("PROJECT_NAME <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("PROJECT_NAME >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_NAME >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("PROJECT_NAME <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_NAME <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("PROJECT_NAME like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("PROJECT_NAME not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("PROJECT_NAME in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("PROJECT_NAME not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("PROJECT_NAME between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("PROJECT_NAME not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeIsNull() {
            addCriterion("PROJECT_REGION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeIsNotNull() {
            addCriterion("PROJECT_REGION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeEqualTo(String value) {
            addCriterion("PROJECT_REGION_CODE =", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeNotEqualTo(String value) {
            addCriterion("PROJECT_REGION_CODE <>", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeGreaterThan(String value) {
            addCriterion("PROJECT_REGION_CODE >", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_REGION_CODE >=", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeLessThan(String value) {
            addCriterion("PROJECT_REGION_CODE <", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_REGION_CODE <=", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeLike(String value) {
            addCriterion("PROJECT_REGION_CODE like", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeNotLike(String value) {
            addCriterion("PROJECT_REGION_CODE not like", value, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeIn(List<String> values) {
            addCriterion("PROJECT_REGION_CODE in", values, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeNotIn(List<String> values) {
            addCriterion("PROJECT_REGION_CODE not in", values, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeBetween(String value1, String value2) {
            addCriterion("PROJECT_REGION_CODE between", value1, value2, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectRegionCodeNotBetween(String value1, String value2) {
            addCriterion("PROJECT_REGION_CODE not between", value1, value2, "projectRegionCode");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentIsNull() {
            addCriterion("PROJECT_EQUIPMENT is null");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentIsNotNull() {
            addCriterion("PROJECT_EQUIPMENT is not null");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentEqualTo(String value) {
            addCriterion("PROJECT_EQUIPMENT =", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentNotEqualTo(String value) {
            addCriterion("PROJECT_EQUIPMENT <>", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentGreaterThan(String value) {
            addCriterion("PROJECT_EQUIPMENT >", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_EQUIPMENT >=", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentLessThan(String value) {
            addCriterion("PROJECT_EQUIPMENT <", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_EQUIPMENT <=", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentLike(String value) {
            addCriterion("PROJECT_EQUIPMENT like", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentNotLike(String value) {
            addCriterion("PROJECT_EQUIPMENT not like", value, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentIn(List<String> values) {
            addCriterion("PROJECT_EQUIPMENT in", values, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentNotIn(List<String> values) {
            addCriterion("PROJECT_EQUIPMENT not in", values, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentBetween(String value1, String value2) {
            addCriterion("PROJECT_EQUIPMENT between", value1, value2, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andProjectEquipmentNotBetween(String value1, String value2) {
            addCriterion("PROJECT_EQUIPMENT not between", value1, value2, "projectEquipment");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeIsNull() {
            addCriterion("RELEASE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeIsNotNull() {
            addCriterion("RELEASE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeEqualTo(Date value) {
            addCriterion("RELEASE_TIME =", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeNotEqualTo(Date value) {
            addCriterion("RELEASE_TIME <>", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeGreaterThan(Date value) {
            addCriterion("RELEASE_TIME >", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RELEASE_TIME >=", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeLessThan(Date value) {
            addCriterion("RELEASE_TIME <", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeLessThanOrEqualTo(Date value) {
            addCriterion("RELEASE_TIME <=", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeIn(List<Date> values) {
            addCriterion("RELEASE_TIME in", values, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeNotIn(List<Date> values) {
            addCriterion("RELEASE_TIME not in", values, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeBetween(Date value1, Date value2) {
            addCriterion("RELEASE_TIME between", value1, value2, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeNotBetween(Date value1, Date value2) {
            addCriterion("RELEASE_TIME not between", value1, value2, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_info
     *
     * @mbggenerated do_not_delete_during_merge Fri May 16 17:10:29 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_info
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}