package com.zzc.hpnote.domain;

import java.util.Date;

public class PriceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.H_ID
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private String hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.TOTAL_PRICE
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private Float totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.AVERAGE_PRICE
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private Float averagePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.DOWN_PAYMENT
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private Float downPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.MONTH_PAYMENT
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private Float monthPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.CREATE_TIME
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_info.REMARK
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.H_ID
     *
     * @return the value of price_info.H_ID
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public String gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.H_ID
     *
     * @param hId the value for price_info.H_ID
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void sethId(String hId) {
        this.hId = hId == null ? null : hId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.TOTAL_PRICE
     *
     * @return the value of price_info.TOTAL_PRICE
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Float getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.TOTAL_PRICE
     *
     * @param totalPrice the value for price_info.TOTAL_PRICE
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.AVERAGE_PRICE
     *
     * @return the value of price_info.AVERAGE_PRICE
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Float getAveragePrice() {
        return averagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.AVERAGE_PRICE
     *
     * @param averagePrice the value for price_info.AVERAGE_PRICE
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setAveragePrice(Float averagePrice) {
        this.averagePrice = averagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.DOWN_PAYMENT
     *
     * @return the value of price_info.DOWN_PAYMENT
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Float getDownPayment() {
        return downPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.DOWN_PAYMENT
     *
     * @param downPayment the value for price_info.DOWN_PAYMENT
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setDownPayment(Float downPayment) {
        this.downPayment = downPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.MONTH_PAYMENT
     *
     * @return the value of price_info.MONTH_PAYMENT
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Float getMonthPayment() {
        return monthPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.MONTH_PAYMENT
     *
     * @param monthPayment the value for price_info.MONTH_PAYMENT
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setMonthPayment(Float monthPayment) {
        this.monthPayment = monthPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.CREATE_TIME
     *
     * @return the value of price_info.CREATE_TIME
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.CREATE_TIME
     *
     * @param createTime the value for price_info.CREATE_TIME
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_info.REMARK
     *
     * @return the value of price_info.REMARK
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_info.REMARK
     *
     * @param remark the value for price_info.REMARK
     *
     * @mbggenerated Fri May 16 17:10:29 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    
	@Override
	public String toString() {
		return "[hId=" + this.hId + ",totalPrice=" + this.totalPrice
				+ ",averagePrice=" + this.averagePrice + ",downPayment="
				+ this.downPayment + ",monthPayment=" + this.monthPayment
				+ ",createTime=" + this.createTime + ",remark=" + this.remark
				+ "]";
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof PriceInfo) {
			return ((PriceInfo) obj).toString().equals(this.toString());
		} else {
			return false;
		}
	}
}