package com.zzc.hpnote.domain;

import java.util.Date;

public class TaskConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_conf.ID
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_conf.TASK_BEG_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Integer taskBegNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_conf.TASK_SEG_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Integer taskSegNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_conf.VERSION
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Date version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_conf.ID
     *
     * @return the value of task_conf.ID
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_conf.ID
     *
     * @param id the value for task_conf.ID
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_conf.TASK_BEG_NUM
     *
     * @return the value of task_conf.TASK_BEG_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Integer getTaskBegNum() {
        return taskBegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_conf.TASK_BEG_NUM
     *
     * @param taskBegNum the value for task_conf.TASK_BEG_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setTaskBegNum(Integer taskBegNum) {
        this.taskBegNum = taskBegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_conf.TASK_SEG_NUM
     *
     * @return the value of task_conf.TASK_SEG_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Integer getTaskSegNum() {
        return taskSegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_conf.TASK_SEG_NUM
     *
     * @param taskSegNum the value for task_conf.TASK_SEG_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setTaskSegNum(Integer taskSegNum) {
        this.taskSegNum = taskSegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_conf.VERSION
     *
     * @return the value of task_conf.VERSION
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Date getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_conf.VERSION
     *
     * @param version the value for task_conf.VERSION
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setVersion(Date version) {
        this.version = version;
    }
}