package com.zzc.hpnote.domain;

import java.util.Date;

public class TaskFailDb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_fail_db.BEG_TASK_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Integer begTaskNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_fail_db.END_TASK_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Integer endTaskNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_fail_db.CREATE_TIME
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_fail_db.BEG_TASK_NUM
     *
     * @return the value of task_fail_db.BEG_TASK_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Integer getBegTaskNum() {
        return begTaskNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_fail_db.BEG_TASK_NUM
     *
     * @param begTaskNum the value for task_fail_db.BEG_TASK_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setBegTaskNum(Integer begTaskNum) {
        this.begTaskNum = begTaskNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_fail_db.END_TASK_NUM
     *
     * @return the value of task_fail_db.END_TASK_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Integer getEndTaskNum() {
        return endTaskNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_fail_db.END_TASK_NUM
     *
     * @param endTaskNum the value for task_fail_db.END_TASK_NUM
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setEndTaskNum(Integer endTaskNum) {
        this.endTaskNum = endTaskNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_fail_db.CREATE_TIME
     *
     * @return the value of task_fail_db.CREATE_TIME
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_fail_db.CREATE_TIME
     *
     * @param createTime the value for task_fail_db.CREATE_TIME
     *
     * @mbggenerated Sun May 25 10:23:34 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}