package com.zzc.netcrawler.domain;

import java.util.Date;

public class NetIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_index.NET_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Integer netId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_index.NET_URL
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String netUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_index.STS_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Integer stsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_index.EXEC_MSG
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String execMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_index.CREATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_index.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_index.NET_ID
     *
     * @return the value of net_index.NET_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Integer getNetId() {
        return netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_index.NET_ID
     *
     * @param netId the value for net_index.NET_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setNetId(Integer netId) {
        this.netId = netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_index.NET_URL
     *
     * @return the value of net_index.NET_URL
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getNetUrl() {
        return netUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_index.NET_URL
     *
     * @param netUrl the value for net_index.NET_URL
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setNetUrl(String netUrl) {
        this.netUrl = netUrl == null ? null : netUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_index.STS_ID
     *
     * @return the value of net_index.STS_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Integer getStsId() {
        return stsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_index.STS_ID
     *
     * @param stsId the value for net_index.STS_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setStsId(Integer stsId) {
        this.stsId = stsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_index.EXEC_MSG
     *
     * @return the value of net_index.EXEC_MSG
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getExecMsg() {
        return execMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_index.EXEC_MSG
     *
     * @param execMsg the value for net_index.EXEC_MSG
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setExecMsg(String execMsg) {
        this.execMsg = execMsg == null ? null : execMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_index.CREATE_TIME
     *
     * @return the value of net_index.CREATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_index.CREATE_TIME
     *
     * @param createTime the value for net_index.CREATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_index.UPDATE_TIME
     *
     * @return the value of net_index.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_index.UPDATE_TIME
     *
     * @param updateTime the value for net_index.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}