package com.zzc.netcrawler.domain;

import java.util.Date;

public class NetInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.NET_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Integer netId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.ENCODE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String encode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.NET_TITLE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String netTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.NET_KEYS
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String netKeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.NET_DESC
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String netDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.CREATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.RES_CODE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private String resCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_info.PARSE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    private Integer parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.NET_ID
     *
     * @return the value of net_info.NET_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Integer getNetId() {
        return netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.NET_ID
     *
     * @param netId the value for net_info.NET_ID
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setNetId(Integer netId) {
        this.netId = netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.ENCODE
     *
     * @return the value of net_info.ENCODE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getEncode() {
        return encode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.ENCODE
     *
     * @param encode the value for net_info.ENCODE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setEncode(String encode) {
        this.encode = encode == null ? null : encode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.NET_TITLE
     *
     * @return the value of net_info.NET_TITLE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getNetTitle() {
        return netTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.NET_TITLE
     *
     * @param netTitle the value for net_info.NET_TITLE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setNetTitle(String netTitle) {
        this.netTitle = netTitle == null ? null : netTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.NET_KEYS
     *
     * @return the value of net_info.NET_KEYS
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getNetKeys() {
        return netKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.NET_KEYS
     *
     * @param netKeys the value for net_info.NET_KEYS
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setNetKeys(String netKeys) {
        this.netKeys = netKeys == null ? null : netKeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.NET_DESC
     *
     * @return the value of net_info.NET_DESC
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getNetDesc() {
        return netDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.NET_DESC
     *
     * @param netDesc the value for net_info.NET_DESC
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setNetDesc(String netDesc) {
        this.netDesc = netDesc == null ? null : netDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.CREATE_TIME
     *
     * @return the value of net_info.CREATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.CREATE_TIME
     *
     * @param createTime the value for net_info.CREATE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.RES_CODE
     *
     * @return the value of net_info.RES_CODE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.RES_CODE
     *
     * @param resCode the value for net_info.RES_CODE
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_info.PARSE_TIME
     *
     * @return the value of net_info.PARSE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public Integer getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_info.PARSE_TIME
     *
     * @param parseTime the value for net_info.PARSE_TIME
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    public void setParseTime(Integer parseTime) {
        this.parseTime = parseTime;
    }
}