package com.zzc.netcrawler.beanset;

import java.util.Date;

public class NetLogOld {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.log_id
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.create_time
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.time_segm
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer timeSegm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.time_unit
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer timeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.all_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer allAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.sts10_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer sts10Amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.sts11_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer sts11Amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.sts12_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer sts12Amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.sts13_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer sts13Amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.sts21_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer sts21Amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.all_ext_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer allExtAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.rq_appd_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer rqAppdAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.wq_pars_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer wqParsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.appd_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer appdAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_log.pars_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    private Integer parsAmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.log_id
     *
     * @return the value of net_log.log_id
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.log_id
     *
     * @param logId the value for net_log.log_id
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.create_time
     *
     * @return the value of net_log.create_time
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.create_time
     *
     * @param createTime the value for net_log.create_time
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.time_segm
     *
     * @return the value of net_log.time_segm
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getTimeSegm() {
        return timeSegm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.time_segm
     *
     * @param timeSegm the value for net_log.time_segm
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setTimeSegm(Integer timeSegm) {
        this.timeSegm = timeSegm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.time_unit
     *
     * @return the value of net_log.time_unit
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getTimeUnit() {
        return timeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.time_unit
     *
     * @param timeUnit the value for net_log.time_unit
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setTimeUnit(Integer timeUnit) {
        this.timeUnit = timeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.all_amt
     *
     * @return the value of net_log.all_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getAllAmt() {
        return allAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.all_amt
     *
     * @param allAmt the value for net_log.all_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setAllAmt(Integer allAmt) {
        this.allAmt = allAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.sts10_amt
     *
     * @return the value of net_log.sts10_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getSts10Amt() {
        return sts10Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.sts10_amt
     *
     * @param sts10Amt the value for net_log.sts10_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setSts10Amt(Integer sts10Amt) {
        this.sts10Amt = sts10Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.sts11_amt
     *
     * @return the value of net_log.sts11_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getSts11Amt() {
        return sts11Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.sts11_amt
     *
     * @param sts11Amt the value for net_log.sts11_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setSts11Amt(Integer sts11Amt) {
        this.sts11Amt = sts11Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.sts12_amt
     *
     * @return the value of net_log.sts12_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getSts12Amt() {
        return sts12Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.sts12_amt
     *
     * @param sts12Amt the value for net_log.sts12_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setSts12Amt(Integer sts12Amt) {
        this.sts12Amt = sts12Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.sts13_amt
     *
     * @return the value of net_log.sts13_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getSts13Amt() {
        return sts13Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.sts13_amt
     *
     * @param sts13Amt the value for net_log.sts13_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setSts13Amt(Integer sts13Amt) {
        this.sts13Amt = sts13Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.sts21_amt
     *
     * @return the value of net_log.sts21_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getSts21Amt() {
        return sts21Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.sts21_amt
     *
     * @param sts21Amt the value for net_log.sts21_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setSts21Amt(Integer sts21Amt) {
        this.sts21Amt = sts21Amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.all_ext_amt
     *
     * @return the value of net_log.all_ext_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getAllExtAmt() {
        return allExtAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.all_ext_amt
     *
     * @param allExtAmt the value for net_log.all_ext_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setAllExtAmt(Integer allExtAmt) {
        this.allExtAmt = allExtAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.rq_appd_amt
     *
     * @return the value of net_log.rq_appd_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getRqAppdAmt() {
        return rqAppdAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.rq_appd_amt
     *
     * @param rqAppdAmt the value for net_log.rq_appd_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setRqAppdAmt(Integer rqAppdAmt) {
        this.rqAppdAmt = rqAppdAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.wq_pars_amt
     *
     * @return the value of net_log.wq_pars_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getWqParsAmt() {
        return wqParsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.wq_pars_amt
     *
     * @param wqParsAmt the value for net_log.wq_pars_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setWqParsAmt(Integer wqParsAmt) {
        this.wqParsAmt = wqParsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.appd_amt
     *
     * @return the value of net_log.appd_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getAppdAmt() {
        return appdAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.appd_amt
     *
     * @param appdAmt the value for net_log.appd_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setAppdAmt(Integer appdAmt) {
        this.appdAmt = appdAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_log.pars_amt
     *
     * @return the value of net_log.pars_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public Integer getParsAmt() {
        return parsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_log.pars_amt
     *
     * @param parsAmt the value for net_log.pars_amt
     *
     * @mbggenerated Mon Mar 17 13:06:00 CST 2014
     */
    public void setParsAmt(Integer parsAmt) {
        this.parsAmt = parsAmt;
    }
}