package com.zzc.netcrawler.beanset;

public class NetStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_status.sts_id
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    private Integer stsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_status.sts_name
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    private String stsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column net_status.note
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_status.sts_id
     *
     * @return the value of net_status.sts_id
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    public Integer getStsId() {
        return stsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_status.sts_id
     *
     * @param stsId the value for net_status.sts_id
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    public void setStsId(Integer stsId) {
        this.stsId = stsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_status.sts_name
     *
     * @return the value of net_status.sts_name
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    public String getStsName() {
        return stsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_status.sts_name
     *
     * @param stsName the value for net_status.sts_name
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    public void setStsName(String stsName) {
        this.stsName = stsName == null ? null : stsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column net_status.note
     *
     * @return the value of net_status.note
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column net_status.note
     *
     * @param note the value for net_status.note
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}