package com.chilicool.reporttool.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chilicool.reporttool.domain.CfgPrintTemplateAttr;
import com.chilicool.reporttool.domain.CfgPrintTemplateAttrExample;

public interface CfgPrintTemplateAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    int countByExample(CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    int deleteByExample(CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    int insert(CfgPrintTemplateAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    int insertSelective(CfgPrintTemplateAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    List<CfgPrintTemplateAttr> selectByExample(CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") CfgPrintTemplateAttr record, @Param("example") CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template_attr
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    int updateByExample(@Param("record") CfgPrintTemplateAttr record, @Param("example") CfgPrintTemplateAttrExample example);
}