package com.chilicool.reporttool.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chilicool.reporttool.domain.CfgPrintTemplate;
import com.chilicool.reporttool.domain.CfgPrintTemplateExample;

public interface CfgPrintTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int countByExample(CfgPrintTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int deleteByExample(CfgPrintTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int deleteByPrimaryKey(String templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int insert(CfgPrintTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int insertSelective(CfgPrintTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    List<CfgPrintTemplate> selectByExample(CfgPrintTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    CfgPrintTemplate selectByPrimaryKey(String templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") CfgPrintTemplate record, @Param("example") CfgPrintTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int updateByExample(@Param("record") CfgPrintTemplate record, @Param("example") CfgPrintTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int updateByPrimaryKeySelective(CfgPrintTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE
     *
     * @mbggenerated Mon Mar 30 15:09:39 CST 2015
     */
    int updateByPrimaryKey(CfgPrintTemplate record);
}