package com.chilicool.reporttool.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chilicool.reporttool.domain.CfgPrintTemplateAttr;
import com.chilicool.reporttool.domain.CfgPrintTemplateAttrExample;

public interface CfgPrintTemplateAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    int countByExample(CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    int deleteByExample(CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    int insert(CfgPrintTemplateAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    int insertSelective(CfgPrintTemplateAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    List<CfgPrintTemplateAttr> selectByExample(CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") CfgPrintTemplateAttr record, @Param("example") CfgPrintTemplateAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PRINT_TEMPLATE_ATTR
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    int updateByExample(@Param("record") CfgPrintTemplateAttr record, @Param("example") CfgPrintTemplateAttrExample example);
}