package com.zzc.netcrawler.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zzc.netcrawler.domain.NetIndex;
import com.zzc.netcrawler.domain.NetIndexExample;
import com.zzc.netcrawler.domain.NetIndexModel;

public interface NetIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int countByExample(NetIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int deleteByExample(NetIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int deleteByPrimaryKey(Integer netId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int insert(NetIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int insertSelective(NetIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    List<NetIndex> selectByExample(NetIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    NetIndex selectByPrimaryKey(Integer netId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int updateByExampleSelective(@Param("record") NetIndex record, @Param("example") NetIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int updateByExample(@Param("record") NetIndex record, @Param("example") NetIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int updateByPrimaryKeySelective(NetIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_index
     *
     * @mbggenerated Tue Jun 10 13:47:13 CST 2014
     */
    int updateByPrimaryKey(NetIndex record);
    
    /**
     * 索引表数据状态统计
     * @return 
     * @author zhangzechen
     * @date 2014-6-11 下午1:50:24
     */
    List<NetIndexModel> selectGroupBySts();
}