package com.zzc.netcrawler.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zzc.netcrawler.domain.NetLog;
import com.zzc.netcrawler.domain.NetLogExample;

public interface NetLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int countByExample(NetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int deleteByExample(NetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int insert(NetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int insertSelective(NetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    List<NetLog> selectByExample(NetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    NetLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int updateByExampleSelective(@Param("record") NetLog record, @Param("example") NetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int updateByExample(@Param("record") NetLog record, @Param("example") NetLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int updateByPrimaryKeySelective(NetLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_log
     *
     * @mbggenerated Wed Jun 11 13:44:16 CST 2014
     */
    int updateByPrimaryKey(NetLog record);
}