package com.zzc.netcrawler.dao;

import com.zzc.netcrawler.domain.NetQueueLog;
import com.zzc.netcrawler.domain.NetQueueLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetQueueLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int countByExample(NetQueueLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int deleteByExample(NetQueueLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int insert(NetQueueLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int insertSelective(NetQueueLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    List<NetQueueLog> selectByExample(NetQueueLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    NetQueueLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int updateByExampleSelective(@Param("record") NetQueueLog record, @Param("example") NetQueueLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int updateByExample(@Param("record") NetQueueLog record, @Param("example") NetQueueLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int updateByPrimaryKeySelective(NetQueueLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_queue_log
     *
     * @mbggenerated Wed Jun 11 15:47:27 CST 2014
     */
    int updateByPrimaryKey(NetQueueLog record);
}