package com.zzc.netcrawler.dao;

import com.zzc.netcrawler.beanset.NetStatus;
import com.zzc.netcrawler.beanset.NetStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    int countByExample(NetStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    int deleteByExample(NetStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    int insert(NetStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    int insertSelective(NetStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    List<NetStatus> selectByExample(NetStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") NetStatus record, @Param("example") NetStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table net_status
     *
     * @mbggenerated Mon Mar 17 12:36:46 CST 2014
     */
    int updateByExample(@Param("record") NetStatus record, @Param("example") NetStatusExample example);
}