package com.chilicool.reporttool.domain;

public class CfgPrintTemplateAttr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PRINT_TEMPLATE_ATTR.TEMPLATE_ID
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PRINT_TEMPLATE_ATTR.ATTR_CODE
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PRINT_TEMPLATE_ATTR.ATTR_VALUE_FORMAT
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    private String attrValueFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PRINT_TEMPLATE_ATTR.NOTE
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PRINT_TEMPLATE_ATTR.TEMPLATE_ID
     *
     * @return the value of CFG_PRINT_TEMPLATE_ATTR.TEMPLATE_ID
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PRINT_TEMPLATE_ATTR.TEMPLATE_ID
     *
     * @param templateId the value for CFG_PRINT_TEMPLATE_ATTR.TEMPLATE_ID
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PRINT_TEMPLATE_ATTR.ATTR_CODE
     *
     * @return the value of CFG_PRINT_TEMPLATE_ATTR.ATTR_CODE
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PRINT_TEMPLATE_ATTR.ATTR_CODE
     *
     * @param attrCode the value for CFG_PRINT_TEMPLATE_ATTR.ATTR_CODE
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PRINT_TEMPLATE_ATTR.ATTR_VALUE_FORMAT
     *
     * @return the value of CFG_PRINT_TEMPLATE_ATTR.ATTR_VALUE_FORMAT
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public String getAttrValueFormat() {
        return attrValueFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PRINT_TEMPLATE_ATTR.ATTR_VALUE_FORMAT
     *
     * @param attrValueFormat the value for CFG_PRINT_TEMPLATE_ATTR.ATTR_VALUE_FORMAT
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public void setAttrValueFormat(String attrValueFormat) {
        this.attrValueFormat = attrValueFormat == null ? null : attrValueFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PRINT_TEMPLATE_ATTR.NOTE
     *
     * @return the value of CFG_PRINT_TEMPLATE_ATTR.NOTE
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PRINT_TEMPLATE_ATTR.NOTE
     *
     * @param note the value for CFG_PRINT_TEMPLATE_ATTR.NOTE
     *
     * @mbggenerated Wed Mar 18 14:51:47 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}