package com.chilicool.reporttool.domain;

import java.util.Date;

public class CfgPrintTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_id
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_name
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_lang
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateLang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_path
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templatePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_group
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_file
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.busi_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.sub_busi_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String subBusiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_pid
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templatePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_version
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_desc
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_bean
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateBean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.template_service
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String templateService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.use_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String useType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.print_name
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String printName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.create_date
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.modify_date
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.state
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.creator
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.org_id
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_print_template.note
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_id
     *
     * @return the value of cfg_print_template.template_id
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_id
     *
     * @param templateId the value for cfg_print_template.template_id
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_name
     *
     * @return the value of cfg_print_template.template_name
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_name
     *
     * @param templateName the value for cfg_print_template.template_name
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_lang
     *
     * @return the value of cfg_print_template.template_lang
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateLang() {
        return templateLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_lang
     *
     * @param templateLang the value for cfg_print_template.template_lang
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateLang(String templateLang) {
        this.templateLang = templateLang == null ? null : templateLang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_path
     *
     * @return the value of cfg_print_template.template_path
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplatePath() {
        return templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_path
     *
     * @param templatePath the value for cfg_print_template.template_path
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath == null ? null : templatePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_group
     *
     * @return the value of cfg_print_template.template_group
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateGroup() {
        return templateGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_group
     *
     * @param templateGroup the value for cfg_print_template.template_group
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateGroup(String templateGroup) {
        this.templateGroup = templateGroup == null ? null : templateGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_file
     *
     * @return the value of cfg_print_template.template_file
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateFile() {
        return templateFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_file
     *
     * @param templateFile the value for cfg_print_template.template_file
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateFile(String templateFile) {
        this.templateFile = templateFile == null ? null : templateFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.busi_type
     *
     * @return the value of cfg_print_template.busi_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.busi_type
     *
     * @param busiType the value for cfg_print_template.busi_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.sub_busi_type
     *
     * @return the value of cfg_print_template.sub_busi_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getSubBusiType() {
        return subBusiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.sub_busi_type
     *
     * @param subBusiType the value for cfg_print_template.sub_busi_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setSubBusiType(String subBusiType) {
        this.subBusiType = subBusiType == null ? null : subBusiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_pid
     *
     * @return the value of cfg_print_template.template_pid
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplatePid() {
        return templatePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_pid
     *
     * @param templatePid the value for cfg_print_template.template_pid
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplatePid(String templatePid) {
        this.templatePid = templatePid == null ? null : templatePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_version
     *
     * @return the value of cfg_print_template.template_version
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateVersion() {
        return templateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_version
     *
     * @param templateVersion the value for cfg_print_template.template_version
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateVersion(String templateVersion) {
        this.templateVersion = templateVersion == null ? null : templateVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_desc
     *
     * @return the value of cfg_print_template.template_desc
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateDesc() {
        return templateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_desc
     *
     * @param templateDesc the value for cfg_print_template.template_desc
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateDesc(String templateDesc) {
        this.templateDesc = templateDesc == null ? null : templateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_bean
     *
     * @return the value of cfg_print_template.template_bean
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateBean() {
        return templateBean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_bean
     *
     * @param templateBean the value for cfg_print_template.template_bean
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateBean(String templateBean) {
        this.templateBean = templateBean == null ? null : templateBean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.template_service
     *
     * @return the value of cfg_print_template.template_service
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getTemplateService() {
        return templateService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.template_service
     *
     * @param templateService the value for cfg_print_template.template_service
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setTemplateService(String templateService) {
        this.templateService = templateService == null ? null : templateService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.use_type
     *
     * @return the value of cfg_print_template.use_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.use_type
     *
     * @param useType the value for cfg_print_template.use_type
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setUseType(String useType) {
        this.useType = useType == null ? null : useType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.print_name
     *
     * @return the value of cfg_print_template.print_name
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getPrintName() {
        return printName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.print_name
     *
     * @param printName the value for cfg_print_template.print_name
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setPrintName(String printName) {
        this.printName = printName == null ? null : printName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.create_date
     *
     * @return the value of cfg_print_template.create_date
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.create_date
     *
     * @param createDate the value for cfg_print_template.create_date
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.modify_date
     *
     * @return the value of cfg_print_template.modify_date
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.modify_date
     *
     * @param modifyDate the value for cfg_print_template.modify_date
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.state
     *
     * @return the value of cfg_print_template.state
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.state
     *
     * @param state the value for cfg_print_template.state
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.creator
     *
     * @return the value of cfg_print_template.creator
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.creator
     *
     * @param creator the value for cfg_print_template.creator
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.org_id
     *
     * @return the value of cfg_print_template.org_id
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.org_id
     *
     * @param orgId the value for cfg_print_template.org_id
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_print_template.note
     *
     * @return the value of cfg_print_template.note
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_print_template.note
     *
     * @param note the value for cfg_print_template.note
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}