package com.chilicool.reporttool.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CfgPrintTemplateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public CfgPrintTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTemplateIdIsNull() {
            addCriterion("template_id is null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNotNull() {
            addCriterion("template_id is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdEqualTo(String value) {
            addCriterion("template_id =", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotEqualTo(String value) {
            addCriterion("template_id <>", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThan(String value) {
            addCriterion("template_id >", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThanOrEqualTo(String value) {
            addCriterion("template_id >=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThan(String value) {
            addCriterion("template_id <", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThanOrEqualTo(String value) {
            addCriterion("template_id <=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLike(String value) {
            addCriterion("template_id like", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotLike(String value) {
            addCriterion("template_id not like", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIn(List<String> values) {
            addCriterion("template_id in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotIn(List<String> values) {
            addCriterion("template_id not in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdBetween(String value1, String value2) {
            addCriterion("template_id between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotBetween(String value1, String value2) {
            addCriterion("template_id not between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNull() {
            addCriterion("template_name is null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNotNull() {
            addCriterion("template_name is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameEqualTo(String value) {
            addCriterion("template_name =", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotEqualTo(String value) {
            addCriterion("template_name <>", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThan(String value) {
            addCriterion("template_name >", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThanOrEqualTo(String value) {
            addCriterion("template_name >=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThan(String value) {
            addCriterion("template_name <", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThanOrEqualTo(String value) {
            addCriterion("template_name <=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLike(String value) {
            addCriterion("template_name like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotLike(String value) {
            addCriterion("template_name not like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIn(List<String> values) {
            addCriterion("template_name in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotIn(List<String> values) {
            addCriterion("template_name not in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameBetween(String value1, String value2) {
            addCriterion("template_name between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotBetween(String value1, String value2) {
            addCriterion("template_name not between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateLangIsNull() {
            addCriterion("template_lang is null");
            return (Criteria) this;
        }

        public Criteria andTemplateLangIsNotNull() {
            addCriterion("template_lang is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateLangEqualTo(String value) {
            addCriterion("template_lang =", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangNotEqualTo(String value) {
            addCriterion("template_lang <>", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangGreaterThan(String value) {
            addCriterion("template_lang >", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangGreaterThanOrEqualTo(String value) {
            addCriterion("template_lang >=", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangLessThan(String value) {
            addCriterion("template_lang <", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangLessThanOrEqualTo(String value) {
            addCriterion("template_lang <=", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangLike(String value) {
            addCriterion("template_lang like", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangNotLike(String value) {
            addCriterion("template_lang not like", value, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangIn(List<String> values) {
            addCriterion("template_lang in", values, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangNotIn(List<String> values) {
            addCriterion("template_lang not in", values, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangBetween(String value1, String value2) {
            addCriterion("template_lang between", value1, value2, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplateLangNotBetween(String value1, String value2) {
            addCriterion("template_lang not between", value1, value2, "templateLang");
            return (Criteria) this;
        }

        public Criteria andTemplatePathIsNull() {
            addCriterion("template_path is null");
            return (Criteria) this;
        }

        public Criteria andTemplatePathIsNotNull() {
            addCriterion("template_path is not null");
            return (Criteria) this;
        }

        public Criteria andTemplatePathEqualTo(String value) {
            addCriterion("template_path =", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathNotEqualTo(String value) {
            addCriterion("template_path <>", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathGreaterThan(String value) {
            addCriterion("template_path >", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathGreaterThanOrEqualTo(String value) {
            addCriterion("template_path >=", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathLessThan(String value) {
            addCriterion("template_path <", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathLessThanOrEqualTo(String value) {
            addCriterion("template_path <=", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathLike(String value) {
            addCriterion("template_path like", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathNotLike(String value) {
            addCriterion("template_path not like", value, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathIn(List<String> values) {
            addCriterion("template_path in", values, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathNotIn(List<String> values) {
            addCriterion("template_path not in", values, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathBetween(String value1, String value2) {
            addCriterion("template_path between", value1, value2, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplatePathNotBetween(String value1, String value2) {
            addCriterion("template_path not between", value1, value2, "templatePath");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupIsNull() {
            addCriterion("template_group is null");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupIsNotNull() {
            addCriterion("template_group is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupEqualTo(String value) {
            addCriterion("template_group =", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupNotEqualTo(String value) {
            addCriterion("template_group <>", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupGreaterThan(String value) {
            addCriterion("template_group >", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupGreaterThanOrEqualTo(String value) {
            addCriterion("template_group >=", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupLessThan(String value) {
            addCriterion("template_group <", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupLessThanOrEqualTo(String value) {
            addCriterion("template_group <=", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupLike(String value) {
            addCriterion("template_group like", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupNotLike(String value) {
            addCriterion("template_group not like", value, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupIn(List<String> values) {
            addCriterion("template_group in", values, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupNotIn(List<String> values) {
            addCriterion("template_group not in", values, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupBetween(String value1, String value2) {
            addCriterion("template_group between", value1, value2, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateGroupNotBetween(String value1, String value2) {
            addCriterion("template_group not between", value1, value2, "templateGroup");
            return (Criteria) this;
        }

        public Criteria andTemplateFileIsNull() {
            addCriterion("template_file is null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileIsNotNull() {
            addCriterion("template_file is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateFileEqualTo(String value) {
            addCriterion("template_file =", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNotEqualTo(String value) {
            addCriterion("template_file <>", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileGreaterThan(String value) {
            addCriterion("template_file >", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileGreaterThanOrEqualTo(String value) {
            addCriterion("template_file >=", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileLessThan(String value) {
            addCriterion("template_file <", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileLessThanOrEqualTo(String value) {
            addCriterion("template_file <=", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileLike(String value) {
            addCriterion("template_file like", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNotLike(String value) {
            addCriterion("template_file not like", value, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileIn(List<String> values) {
            addCriterion("template_file in", values, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNotIn(List<String> values) {
            addCriterion("template_file not in", values, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileBetween(String value1, String value2) {
            addCriterion("template_file between", value1, value2, "templateFile");
            return (Criteria) this;
        }

        public Criteria andTemplateFileNotBetween(String value1, String value2) {
            addCriterion("template_file not between", value1, value2, "templateFile");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIsNull() {
            addCriterion("busi_type is null");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIsNotNull() {
            addCriterion("busi_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusiTypeEqualTo(String value) {
            addCriterion("busi_type =", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotEqualTo(String value) {
            addCriterion("busi_type <>", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeGreaterThan(String value) {
            addCriterion("busi_type >", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("busi_type >=", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeLessThan(String value) {
            addCriterion("busi_type <", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeLessThanOrEqualTo(String value) {
            addCriterion("busi_type <=", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeLike(String value) {
            addCriterion("busi_type like", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotLike(String value) {
            addCriterion("busi_type not like", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIn(List<String> values) {
            addCriterion("busi_type in", values, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotIn(List<String> values) {
            addCriterion("busi_type not in", values, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeBetween(String value1, String value2) {
            addCriterion("busi_type between", value1, value2, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotBetween(String value1, String value2) {
            addCriterion("busi_type not between", value1, value2, "busiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeIsNull() {
            addCriterion("sub_busi_type is null");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeIsNotNull() {
            addCriterion("sub_busi_type is not null");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeEqualTo(String value) {
            addCriterion("sub_busi_type =", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeNotEqualTo(String value) {
            addCriterion("sub_busi_type <>", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeGreaterThan(String value) {
            addCriterion("sub_busi_type >", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sub_busi_type >=", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeLessThan(String value) {
            addCriterion("sub_busi_type <", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeLessThanOrEqualTo(String value) {
            addCriterion("sub_busi_type <=", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeLike(String value) {
            addCriterion("sub_busi_type like", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeNotLike(String value) {
            addCriterion("sub_busi_type not like", value, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeIn(List<String> values) {
            addCriterion("sub_busi_type in", values, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeNotIn(List<String> values) {
            addCriterion("sub_busi_type not in", values, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeBetween(String value1, String value2) {
            addCriterion("sub_busi_type between", value1, value2, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andSubBusiTypeNotBetween(String value1, String value2) {
            addCriterion("sub_busi_type not between", value1, value2, "subBusiType");
            return (Criteria) this;
        }

        public Criteria andTemplatePidIsNull() {
            addCriterion("template_pid is null");
            return (Criteria) this;
        }

        public Criteria andTemplatePidIsNotNull() {
            addCriterion("template_pid is not null");
            return (Criteria) this;
        }

        public Criteria andTemplatePidEqualTo(String value) {
            addCriterion("template_pid =", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidNotEqualTo(String value) {
            addCriterion("template_pid <>", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidGreaterThan(String value) {
            addCriterion("template_pid >", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidGreaterThanOrEqualTo(String value) {
            addCriterion("template_pid >=", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidLessThan(String value) {
            addCriterion("template_pid <", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidLessThanOrEqualTo(String value) {
            addCriterion("template_pid <=", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidLike(String value) {
            addCriterion("template_pid like", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidNotLike(String value) {
            addCriterion("template_pid not like", value, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidIn(List<String> values) {
            addCriterion("template_pid in", values, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidNotIn(List<String> values) {
            addCriterion("template_pid not in", values, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidBetween(String value1, String value2) {
            addCriterion("template_pid between", value1, value2, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplatePidNotBetween(String value1, String value2) {
            addCriterion("template_pid not between", value1, value2, "templatePid");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionIsNull() {
            addCriterion("template_version is null");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionIsNotNull() {
            addCriterion("template_version is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionEqualTo(String value) {
            addCriterion("template_version =", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionNotEqualTo(String value) {
            addCriterion("template_version <>", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionGreaterThan(String value) {
            addCriterion("template_version >", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionGreaterThanOrEqualTo(String value) {
            addCriterion("template_version >=", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionLessThan(String value) {
            addCriterion("template_version <", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionLessThanOrEqualTo(String value) {
            addCriterion("template_version <=", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionLike(String value) {
            addCriterion("template_version like", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionNotLike(String value) {
            addCriterion("template_version not like", value, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionIn(List<String> values) {
            addCriterion("template_version in", values, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionNotIn(List<String> values) {
            addCriterion("template_version not in", values, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionBetween(String value1, String value2) {
            addCriterion("template_version between", value1, value2, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateVersionNotBetween(String value1, String value2) {
            addCriterion("template_version not between", value1, value2, "templateVersion");
            return (Criteria) this;
        }

        public Criteria andTemplateDescIsNull() {
            addCriterion("template_desc is null");
            return (Criteria) this;
        }

        public Criteria andTemplateDescIsNotNull() {
            addCriterion("template_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateDescEqualTo(String value) {
            addCriterion("template_desc =", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescNotEqualTo(String value) {
            addCriterion("template_desc <>", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescGreaterThan(String value) {
            addCriterion("template_desc >", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescGreaterThanOrEqualTo(String value) {
            addCriterion("template_desc >=", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescLessThan(String value) {
            addCriterion("template_desc <", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescLessThanOrEqualTo(String value) {
            addCriterion("template_desc <=", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescLike(String value) {
            addCriterion("template_desc like", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescNotLike(String value) {
            addCriterion("template_desc not like", value, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescIn(List<String> values) {
            addCriterion("template_desc in", values, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescNotIn(List<String> values) {
            addCriterion("template_desc not in", values, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescBetween(String value1, String value2) {
            addCriterion("template_desc between", value1, value2, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateDescNotBetween(String value1, String value2) {
            addCriterion("template_desc not between", value1, value2, "templateDesc");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanIsNull() {
            addCriterion("template_bean is null");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanIsNotNull() {
            addCriterion("template_bean is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanEqualTo(String value) {
            addCriterion("template_bean =", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanNotEqualTo(String value) {
            addCriterion("template_bean <>", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanGreaterThan(String value) {
            addCriterion("template_bean >", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanGreaterThanOrEqualTo(String value) {
            addCriterion("template_bean >=", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanLessThan(String value) {
            addCriterion("template_bean <", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanLessThanOrEqualTo(String value) {
            addCriterion("template_bean <=", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanLike(String value) {
            addCriterion("template_bean like", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanNotLike(String value) {
            addCriterion("template_bean not like", value, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanIn(List<String> values) {
            addCriterion("template_bean in", values, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanNotIn(List<String> values) {
            addCriterion("template_bean not in", values, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanBetween(String value1, String value2) {
            addCriterion("template_bean between", value1, value2, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateBeanNotBetween(String value1, String value2) {
            addCriterion("template_bean not between", value1, value2, "templateBean");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceIsNull() {
            addCriterion("template_service is null");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceIsNotNull() {
            addCriterion("template_service is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceEqualTo(String value) {
            addCriterion("template_service =", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceNotEqualTo(String value) {
            addCriterion("template_service <>", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceGreaterThan(String value) {
            addCriterion("template_service >", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceGreaterThanOrEqualTo(String value) {
            addCriterion("template_service >=", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceLessThan(String value) {
            addCriterion("template_service <", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceLessThanOrEqualTo(String value) {
            addCriterion("template_service <=", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceLike(String value) {
            addCriterion("template_service like", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceNotLike(String value) {
            addCriterion("template_service not like", value, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceIn(List<String> values) {
            addCriterion("template_service in", values, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceNotIn(List<String> values) {
            addCriterion("template_service not in", values, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceBetween(String value1, String value2) {
            addCriterion("template_service between", value1, value2, "templateService");
            return (Criteria) this;
        }

        public Criteria andTemplateServiceNotBetween(String value1, String value2) {
            addCriterion("template_service not between", value1, value2, "templateService");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNull() {
            addCriterion("use_type is null");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNotNull() {
            addCriterion("use_type is not null");
            return (Criteria) this;
        }

        public Criteria andUseTypeEqualTo(String value) {
            addCriterion("use_type =", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotEqualTo(String value) {
            addCriterion("use_type <>", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThan(String value) {
            addCriterion("use_type >", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("use_type >=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThan(String value) {
            addCriterion("use_type <", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThanOrEqualTo(String value) {
            addCriterion("use_type <=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLike(String value) {
            addCriterion("use_type like", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotLike(String value) {
            addCriterion("use_type not like", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeIn(List<String> values) {
            addCriterion("use_type in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotIn(List<String> values) {
            addCriterion("use_type not in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeBetween(String value1, String value2) {
            addCriterion("use_type between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotBetween(String value1, String value2) {
            addCriterion("use_type not between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andPrintNameIsNull() {
            addCriterion("print_name is null");
            return (Criteria) this;
        }

        public Criteria andPrintNameIsNotNull() {
            addCriterion("print_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrintNameEqualTo(String value) {
            addCriterion("print_name =", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameNotEqualTo(String value) {
            addCriterion("print_name <>", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameGreaterThan(String value) {
            addCriterion("print_name >", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameGreaterThanOrEqualTo(String value) {
            addCriterion("print_name >=", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameLessThan(String value) {
            addCriterion("print_name <", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameLessThanOrEqualTo(String value) {
            addCriterion("print_name <=", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameLike(String value) {
            addCriterion("print_name like", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameNotLike(String value) {
            addCriterion("print_name not like", value, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameIn(List<String> values) {
            addCriterion("print_name in", values, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameNotIn(List<String> values) {
            addCriterion("print_name not in", values, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameBetween(String value1, String value2) {
            addCriterion("print_name between", value1, value2, "printName");
            return (Criteria) this;
        }

        public Criteria andPrintNameNotBetween(String value1, String value2) {
            addCriterion("print_name not between", value1, value2, "printName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modify_date is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modify_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterionForJDBCDate("modify_date =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("modify_date <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterionForJDBCDate("modify_date >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("modify_date >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterionForJDBCDate("modify_date <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("modify_date <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterionForJDBCDate("modify_date in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("modify_date not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("modify_date between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("modify_date not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("org_id like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("org_id not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cfg_print_template
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 25 15:37:38 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cfg_print_template
     *
     * @mbggenerated Mon Apr 25 15:37:38 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}